# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.6.0

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t helloworld .
      - run:
         name: docker push
         command: |
           docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
           docker tag helloworld $DOCKER_USER/doojinschool_docker:${CIRCLE_SHA1:0:4}
           docker push $DOCKER_USER/doojinschool_docker
